# ===== Brews =====

brew "awscli"
brew "wget"
brew "python"
brew "git"
brew "thefuck"
brew "autojump"

# ===== Casks =====

# Browsers
cask "google-chrome"
cask "brave-browser"

# Developer Tools
cask "atom"
cask "postman"
cask "iterm2"
cask "docker"

# Productivity
cask "evernote"
cask "1password"
cask "teamviewer"
cask "google-backup-and-sync"

# Entertainment
cask "spotify"
cask "vlc"

# Messaging
cask "caprine"
cask "slack"
cask "telegram"

# Other useful apps
cask "appcleaner"
cask "spectacle"
