# ===== Brews =====

brew "autojump"
brew "awscli"
brew "git"
brew "mas"
brew "python"
brew "tmux"
brew "thefuck"
brew "wget"

# ===== Casks =====

# Browsers
cask "brave-browser"
cask "google-chrome"

# Developer Tools
cask "atom"
cask "docker"
cask "iterm2"
cask "postman"

# Productivity
cask "evernote"
cask "1password"
cask "teamviewer"
cask "google-backup-and-sync"

# Entertainment
cask "spotify"
cask "vlc"

# Messaging
cask "caprine"
cask "slack"
cask "telegram"

# Other useful apps
cask "appcleaner"
cask "authy"
cask "puush"
cask "real-vnc"
cask "spectacle"

# ===== Mac Apple Store =====

mas "Trello", id: 1278508951
